version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2.26-cli-stretch
    working_directory: ~/govinfo
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install json
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: ./vendor/bin/phpunit --log-junit result.xml
      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
                     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                     chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build -r 96c631bd438b491caa133d73b02c7f6b85e916a40667998a6c470a0b5d1c3b89
            sudo ./vendor/bin/phpunit --coverage-clover clover.xml
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
