version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2.26-cli-stretch
    working_directory: ~/govinfo
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install json
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: ./vendor/bin/phpunit --log-junit
      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output
